### ISSUE TITLE
Unable to get setup

### ISSUE THREAD

**Issue by steroberts89** [Wouter0100/freescout-postal#1]
Hey, Awesome module!

I'm trying to get started with this module, I've got it installed however When I change the dropdown to "Postal - HTTP endpoint" Nothing happens, 

I'd expect to see a webhook url as shown in https://github.com/freescout-helpdesk/freescout/pull/1593

Thanks
Stephen

**Comment by Wouter0100** [comment]
Correct, unfortunately - to get that Merge Request merged the implementation required significant changes and I haven't found the time on making the freescout-postal module compatible with the changes introduced in that merge request. 

I'm still running on the first commit of that merge reuqest, only [this](https://github.com/freescout-helpdesk/freescout/pull/1593/commits/33767a590ad05694203e492b8b40f6aa511e7c7e) commit.

**Comment by sentiasa** [comment]
I also wish it was there.

**Comment by Wouter0100** [comment]
You guys should be able to run it, with the commit I linked and the code in this repository. However, some time should be put into it to make sure that it is compatible with all changes introduced in that PR.

**Comment by Wouter0100** [comment]
I patched the module to work with FreeScout. I tested it against **FreeScout 1.8.35** running **PHP 8.0**.

I was unable to get things working in **PHP 8.1**, as this required overrides, which I don't have the time for.
